"""Core data types: menu items, restaurants, order constraints and bundles."""
from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from datetime import datetime, time
from pathlib import Path

GST_RATE = 0.05
ALLERGENS = ["peanut", "tree_nut", "dairy", "gluten", "egg", "soy", "sesame", "fish", "shellfish", "mustard"]
VEG_DIETS = {"veg", "vegan"}
MAIN_COURSES = {"main"}
CARB_COURSES = {"rice", "bread", "noodles"}
MEAL_COURSES = {"meal"}  # biryani, thali, dosa: count as a main AND a carb serving
EXTRA_COURSES = {"starter", "side", "dessert", "beverage"}

DATA_DIR = Path(__file__).parent / "data"
DATA_FILE = DATA_DIR / "restaurants.json"          # hand-curated core: the design doc's examples and traps
EXTRA_FILE = DATA_DIR / "catalog_extra.json"       # generated by data/generate_catalog.py
INGREDIENT_ALLERGENS_FILE = DATA_DIR / "ingredient_allergens.json"


@dataclass
class Item:
    id: str
    name: str
    course: str
    price: int
    serves: float
    diet: str
    contains: list[str]
    may_contain: list[str]
    ingredients: list[str]
    primary: list[str]
    spice: int
    tastes: dict[str, int]
    famous_in: list[str]
    tags: list[str]
    rating: float
    orders_30d: int
    in_stock: bool = True
    allergen_verified: bool = True

    @property
    def is_veg(self) -> bool:
        return self.diet in VEG_DIETS

    @property
    def main_servings(self) -> float:
        return self.serves if self.course in MAIN_COURSES | MEAL_COURSES else 0

    @property
    def carb_servings(self) -> float:
        return self.serves if self.course in CARB_COURSES | MEAL_COURSES else 0

    def allergens(self) -> set[str]:
        return set(self.contains) | set(self.may_contain)


@dataclass
class Restaurant:
    id: str
    name: str
    cuisines: list[str]
    rating: float
    pure_veg: bool
    prep_time_min: int
    distance_km: float
    delivery_fee: int
    packaging_fee: int
    kitchen_flags: list[str]
    open: str
    close: str
    items: list[Item]

    @property
    def fees(self) -> int:
        return self.delivery_fee + self.packaging_fee

    def is_open(self, now: datetime) -> bool:
        o, c = (time.fromisoformat(t) for t in (self.open, self.close))
        return o <= now.time() <= c


def load_data() -> tuple[list[Restaurant], dict]:
    """The catalog (restaurants with menus, user profile), read from Postgres. See db.py.

    FOODAGENT_CATALOG=fixture loads the fixed seed file instead; the test suite sets it so tests
    never depend on a live database someone may have edited.
    """
    if os.environ.get("FOODAGENT_CATALOG") == "fixture":
        return catalog_from_seed(read_json())
    from .db import load_catalog
    return load_catalog()


def read_json(path: Path = DATA_FILE) -> dict:
    """A raw seed file, as `python -m foodagent.db init` loads it into Postgres."""
    return json.loads(Path(path).read_text())


def catalog_from_seed(raw: dict) -> tuple[list[Restaurant], dict]:
    restaurants = [Restaurant(**{**r, "items": [Item(**i) for i in r["items"]]}) for r in raw["restaurants"]]
    return restaurants, raw.get("user_profile", {})


@dataclass
class Constraints:
    """Everything the customer asked for. Hard constraints are enforced; soft ones only rank."""

    headcount: int | None = None
    veg_count: int = 0
    all_veg: bool = False
    allergens: set[str] = field(default_factory=set)
    budget_max: int | None = None
    deliver_by: datetime | None = None
    include_ingredients: list[str] = field(default_factory=list)
    exclude_ingredients: list[str] = field(default_factory=list)
    spice_min: int | None = None
    spice_max: int | None = None
    tastes: dict[str, int] = field(default_factory=dict)  # taste -> minimum intensity (0-4)
    cuisines: list[str] = field(default_factory=list)
    region: str | None = None
    meal: str | None = None
    allow_egg: bool = False          # vegetarians who eat egg ("eggetarian")
    severe: bool = False             # severe/anaphylactic: also drop shared-fryer / cross-contact kitchens
    service_style: str = "shared"    # "plated" is accepted but treated as shared (stricter, safer)
    address_id: str | None = None
    notes: list[str] = field(default_factory=list)  # assumptions the agent should say out loud

    @property
    def mode(self) -> str:
        return "meal" if self.headcount else "dishes"

    @property
    def effective_veg(self) -> int:
        if not self.headcount:
            return 0
        return self.headcount if self.all_veg else min(self.veg_count, self.headcount)

    def update(self, fields: dict) -> None:
        """Merge parsed fields into the current constraints (later messages refine earlier ones)."""
        for key, value in fields.items():
            if value in (None, [], {}, ""):
                continue
            if key == "allergens":
                self.allergens |= set(value)
            elif key == "notes":
                self.notes += [n for n in value if n not in self.notes]
            elif key in ("include_ingredients", "exclude_ingredients", "cuisines"):
                current = getattr(self, key)
                current += [v for v in value if v not in current]
            elif key == "tastes":
                self.tastes.update(value)
            elif key in ("allow_egg", "severe") and not value:
                continue
            else:
                setattr(self, key, value)
        if self.headcount and self.veg_count > self.headcount:
            self.veg_count = self.headcount

    def summary(self) -> str:
        parts = []
        if self.headcount:
            veg = "all veg" if self.all_veg else (f"{self.veg_count} veg" if self.veg_count else "")
            parts.append(f"{self.headcount} people" + (f" ({veg})" if veg else ""))
        if self.allergens:
            parts.append(("severe allergy: " if self.severe else "no ")
                         + ", ".join(sorted(a.replace("_", " ") for a in self.allergens)))
        if self.budget_max:
            parts.append(f"≤ ₹{self.budget_max:,}")
        if self.deliver_by:
            parts.append(f"by {self.deliver_by:%H:%M}")
        if self.spice_min:
            parts.append(f"spice ≥ {self.spice_min}")
        if self.spice_max is not None:
            parts.append(f"spice ≤ {self.spice_max}")
        if self.include_ingredients:
            parts.append("with " + ", ".join(self.include_ingredients))
        if self.exclude_ingredients:
            parts.append("without " + ", ".join(self.exclude_ingredients))
        if self.tastes:
            parts.append(", ".join(self.tastes))
        if self.cuisines:
            parts.append(", ".join(c.replace("_", " ") for c in self.cuisines))
        if self.region:
            parts.append(f"famous in {self.region.title()}")
        return " · ".join(parts) or "no constraints yet"


@dataclass
class Line:
    item: Item
    qty: int


@dataclass
class Bundle:
    restaurant: Restaurant
    lines: list[Line]
    eta: datetime | None = None
    margin_min: int | None = None
    score: float = 0.0
    reasons: list[str] = field(default_factory=list)
    excluded: list[str] = field(default_factory=list)  # items left out for safety, with why
    bundle_id: str | None = None

    @property
    def subtotal(self) -> int:
        return sum(l.item.price * l.qty for l in self.lines)

    @property
    def gst(self) -> float:
        return round(self.subtotal * GST_RATE, 2)

    @property
    def total(self) -> float:
        return self.subtotal + self.gst + self.restaurant.fees

    @property
    def main_servings(self) -> float:
        return sum(l.item.main_servings * l.qty for l in self.lines)

    @property
    def carb_servings(self) -> float:
        return sum(l.item.carb_servings * l.qty for l in self.lines)

    @property
    def veg_main_servings(self) -> float:
        return sum(l.item.main_servings * l.qty for l in self.lines if l.item.is_veg)

    def veg_servings(self, allow_egg: bool = False) -> float:
        return sum(l.item.main_servings * l.qty for l in self.lines
                   if l.item.is_veg or (allow_egg and l.item.diet == "egg"))

    @property
    def veg_main_dishes(self) -> int:
        return sum(1 for l in self.lines if l.item.is_veg and l.item.main_servings)

    def copy(self) -> "Bundle":
        return Bundle(self.restaurant, [Line(l.item, l.qty) for l in self.lines], self.eta,
                      self.margin_min, self.score, list(self.reasons), list(self.excluded), self.bundle_id)
